-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 13:29:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema finalproject7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finalproject7` DEFAULT CHARACTER SET utf8mb3 ;
USE `finalproject7` ;
-- -----------------------------------------------------
-- Table `finalproject7`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject7`.`hibernate_sequence` (
  `next_val` BIGINT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;
-- -----------------------------------------------------
-- Table `finalproject7`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject7`.`post` (
  `postId` INT NOT NULL,
  `postName` VARCHAR(200) NULL DEFAULT NULL,
  `postDescription` VARCHAR(200) NULL DEFAULT NULL,
  `postUrl` VARCHAR(100) NULL DEFAULT NULL,
  `postUser` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`postId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
